### ISSUE TITLE
Still Image URL

### ISSUE THREAD

**Issue by Jinx735** [mouldybread/DCS-6100LH#10]
Hi, 
firstly thank for making this great repo. Maybe you already mentioned it, but i couldnt find anything about it.

My question:
Did you also find a link, that only shows the current frame/image?

Cause i want to integrate my camera into Home Assistant and it seems to only work (at least for me i guess) when a Still Image URL is provided.

Thanks

**Comment by m-kloeckner** [comment]
@Jinx735 Apparently I am as clueless as you were. Can you please share the URL for the still image?
