### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by toni1506mc** [mouldybread/DCS-6100LH#2]
hey,

I need help with integrating the camera into Home Assistant. Integrating as a generic camera did not work with the specified url. A stream via vlc with the url works without problems.

What am I doing wrong?

**Comment by mouldybread** [comment]
What version is your firmware?

I use webrtc: https://github.com/AlexxIT/WebRTC

And my card looks like this:
```
type: custom:webrtc-camera
url: rtsp://admin:PINCODE@IP:554/live/profile.1/video
```
