### ISSUE TITLE
How did you add the cam to the network without adding it to myDLINK? 

### ISSUE THREAD

**Issue by hcbille** [mouldybread/DCS-6100LH#3]
Or did you add it to mydlink and just block the network traffic?

**Comment by ErikAndren** [comment]
Yes, that is what I did.

**Comment by mouldybread** [comment]
I also used mydlink to setup the device and blocked network traffic after completing a successful onboarding.

It may be that if you interrupt the setup before it times out(and notices the lack of internet) the device remains connected to the wifi. Worth testing if you get the chance.

**Comment by hcbille** [comment]
> It may be that if you interrupt the setup before it times out(and notices the lack of internet) the device remains connected to the wifi. Worth testing if you get the chance.


I ended up with blacklisting the domain in my DNS, so when I did the setup in the app it just timed out and stayed connected. 
Super smooth.

**Comment by hcbille** [comment]
Closing this!

**Comment by hcbille** [comment]
Closing this!

**Comment by mouldybread** [comment]
Great, what was the domain you blacklisted?

**Comment by stratosgear** [comment]
Yes, another request for getting the blacklisted domain, please....

**Comment by mouldybread** [comment]
I suspect *.mydlink.com will do the trick, though I haven't tested it. I have opted to isolate the camera entirely.

**Comment by stratosgear** [comment]
Actually that makes sense.  I do not see the reason why the camera should connect to ANY external domain.  I'll completely firewall the camera IP.  Thanks!

**Comment by fightforlife** [comment]
I tried blocking DNS Ports and/or blocking all Internet access for the camera. But for me this leads to a very instable RTSP stream.
As soon as soon as I allow access again, the RTSP stream is stable.
Maybe the cloud watchdog is restarting some services.

**Comment by Dryparn** [comment]
All 4 of mine are unstable all the time, regardless if blocked or not. They spontaneously reboot every now and then rendering them totally useless because the stream breaks.

**Comment by mouldybread** [comment]
> All 4 of mine are unstable all the time, regardless if blocked or not. They spontaneously reboot every now and then rendering them totally useless because the stream breaks.

How are you powering them? They're quite thirsty, a good quality 5V/3a pack might be worth a try to see if it makes a difference. You could also try using something like go2rtc to govern the stream. Heat might also be a consideration. 

> I tried blocking DNS Ports and/or blocking all Internet access for the camera. But for me this leads to a very instable RTSP stream. As soon as soon as I allow access again, the RTSP stream is stable. Maybe the cloud watchdog is restarting some services.

A bit late but I don't have this issue with V1.03. My device isn't rooted, I just isolated it.

**Comment by Dryparn** [comment]
I tried with a 2amp pack with no difference. I also measured the power draw on the usb socket and it maxed out at 1.8W.
Two of the devices are rooted and the other 2 are not. I really don't understand what is the problem.

**Comment by fightforlife** [comment]
What router are you using? I suspect my Fritzbox 7590 ax to drop devices on 2.4g wifi when there are too many. (Especially a lot of small devices like sockets and lamps for home automation)
